
steps:
  # Install dependencies
  - name: 'node:20.11.1'
    entrypoint: npm
    args: ['install']

  # Run tests
  - name: 'node:20.11.1'
    entrypoint: npm
    args: ['test']

  # Build the application
  - name: 'node:20.11.1'
    entrypoint: npm
    args: ['run', 'build']

  # Docker build
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA',
      '.'
    ]

  # Push the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA']

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'

substitutions:
  _SERVICE_NAME: nodejs-app  # Default service name
  _REGION: us-central1      # Default region

images:
  - 'gcr.io/$PROJECT_ID/${_SERVICE_NAME}:$COMMIT_SHA'

timeout: '1800s' 